version: '2'

services:
  server:
    image: registry.gitlab.com/matthew-beckett/netxms-dockerfiles/server:3-8-382
    ports:
    - "4700:4700"
    - "4701:4701"

  webui:
    image: registry.gitlab.com/matthew-beckett/netxms-dockerfiles/webui:3-8-382
    ports:
    - "8080:8080"
    environment:
    - "NETXMS_SERVER=server"

  # webuirest:
  #   image: registry.gitlab.com/matthew-beckett/netxms-dockerfiles/webuirest:3-8-382
  #   ports:
  #   - "8080:8080"
  #   environment:
  #   - "NETXMS_SERVER=server"
  #   - "NETXMS_PORT=4701"

  agent:
    image: registry.gitlab.com/matthew-beckett/netxms-dockerfiles/nxagent:3-8-382
    environment:
    - "NXAGENT_CONFIG=MasterServer=server\nLogFile=/var/log/nxagentsome.log\nEnableProxy=yes\nEnableSNMPProxy=yes"
    - "NXAGENT_MASTERSERVERS=server"
    - "NXAGENT_REGISTERSERVER=server"
