#!/bin/bash

if [ ! -e "/data/.initialized" ];
then
	echo "Generating NetXMS server config file /opt/netxmsd/netxmsd.conf"
	mkdir -p /opt/netxmsd
	echo -e "Logfile=/data/netxms.log\n" >> /opt/netxmsd/netxmsd.conf
    
    if [ -v "$NETXMS_DB_DRIVER" ];
    then
        echo -e "DBDriver=${NETXMS_DB_DRIVER}.ddr\n" >> /opt/netxmsd/netxmsd.conf
    else
        echo -e "DBDriver=sqlite.ddr\n" >> /opt/netxmsd/netxmsd.conf
        export NETXMS_DB_DRIVER="sqlite"
    fi
    
    if [ -v "$NETXMS_DB_NAME" ];
    then
        echo -e "DBName=${NETXMS_DB_NAME}" >> /opt/netxmsd/netxmsd.conf
    else
        if [ $NETXMS_DB_DRIVER == "sqlite" ];
        then
            echo -e "DBName=/data/netxms.db" >> /opt/netxmsd/netxmsd.conf
            export NETXMS_DB_NAME="/data/netxms.db"
        else
            echo -e "DBName=netxms" >> /opt/netxmsd/netxmsd.conf
            export NETXMS_DB_NAME="netxms"
        fi
    fi

    if [ -v "$NETXMS_DB_SERVER" ];
    then
        echo -e "DBServer=${NETXMS_DB_SERVER}" >> /opt/netxmsd/netxmsd.conf
    fi

    if [ -v "$NETXMS_DB_LOGIN" ];
    then
        echo -e "DBLogin=${NETXMS_DB_LOGIN}" >> /opt/netxmsd/netxmsd.conf
    fi

    if [ -v "$NETXMS_DB_PASSWORD" ];
    then
        echo -e "DBPasssword=${NETXMS_DB_PASSWORD}\n" >> /opt/netxmsd/netxmsd.conf
    fi

	echo "$NETXMS_CONFIG" >> /opt/netxmsd/netxmsd.conf

	echo "Initializing NetXMS database"
    if [ $NETXMS_DB_DRIVER == "sqlite" ];
    then
        if [ -e $NETXMS_DB_NAME ];
        then
        	echo "Unlocking database"
            echo "Y"|nxdbmgr -c /opt/netxmsd/netxmsd.conf unlock
        fi
    fi
	nxdbmgr -c /opt/netxmsd/netxmsd.conf init

	touch /data/.initialized
fi

# Fix SMS kannel Drv
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libcurl.so.4
if [ -n "$NETXMS_UNLOCKONSTARTUP" ];
then
	echo "Unlocking database"
	echo "Y"|nxdbmgr -c /opt/netxmsd/netxmsd.conf unlock
fi
